<<<<<<< HEAD
# Welcome to Jekyll!
=======
achieve# Welcome to Jekyll!
>>>>>>> dba047bafab8e7a2338f6a0162db352514cbc63b
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

<<<<<<< HEAD
# Site settings
title: loyxin
brief-intro: Lost in physics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rafrozen.cn" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
# twitter_username: gaohaoyang126
# facebook_username: gaohaoyang.water
github_username:  rafrozen
email: luox46@mail2.sysu.edu.cn
# weibo_username: 3115521wh
# # zhihu_username: gaohaoyang
# linkedIn_username: gaohaoyang
# dribbble_username:

description_footer: 特工

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: loyxin

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-96907078-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
=======

# Site settings
title: loyxin
description: waiting for you
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rafrozen.cn"
permalink: "/achieve/:title/"


# Social networking links used in footer. Update and remove as you like.
github_username: rafrozen
email: rafrozenluoxin@gmail.com
# twitter_username:
# facebook_username:
#
# deviantart_username:
# 500px_username:
# flickr_username:
# instagram_username:
# linkedIn_username:



# Analytics and webmaster tools stuff goes here
google_analytics:   UA-96907078-1
google_verify: google0dc287dfe35853fc.html
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 5A2815C4491757B7212F135D94081DEE


# Files
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png

search: true
share: true
comments: true

# Owner/author information
owner:
  name:   loyxin
  avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Waiting For You


#dependencies
# Gems
gems:
  - jekyll-paginate

# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
    syntax_highlighter: rouge
sass:
    style:          :compressed
paginate: 20
paginate_path: "/achieve/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"
>>>>>>> dba047bafab8e7a2338f6a0162db352514cbc63b
